### ISSUE TITLE
ModuleNotFoundError: No module named 'ott.core'

### ISSUE THREAD

**Issue by stefanpeidli** [theislab/moscot#493]
Hi,

I have problems importing moscot:
```
>>> import moscot as mt
/fast/users/peidlis_c/work/miniconda/envs/moscot_env/lib/python3.9/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fast/users/peidlis_c/work/miniconda/envs/moscot_env/lib/python3.9/site-packages/moscot/__init__.py", line 5, in <module>
    import moscot.backends
  File "/fast/users/peidlis_c/work/miniconda/envs/moscot_env/lib/python3.9/site-packages/moscot/backends/__init__.py", line 2, in <module>
    import moscot.backends.ott
  File "/fast/users/peidlis_c/work/miniconda/envs/moscot_env/lib/python3.9/site-packages/moscot/backends/ott/__init__.py", line 1, in <module>
    from moscot.backends.ott._output import OTTOutput
  File "/fast/users/peidlis_c/work/miniconda/envs/moscot_env/lib/python3.9/site-packages/moscot/backends/ott/_output.py", line 6, in <module>
    from ott.core.sinkhorn import SinkhornOutput as OTTSinkhornOutput
ModuleNotFoundError: No module named 'ott.core'
```

I've installed moscot via pip from PyPI into a fresh conda environment with python=3.8. The exact same error occurs on my local Mac with M1 chip and on a linux server.

Thanks in advance for any help!

**Comment by giovp** [comment]
@stefanpeidli I would install from main, pypi release exist but not reliable yet as many ongoing changes, thank you!

**Comment by stefanpeidli** [comment]
Don't worry. Install from main worked fine, thanks!
